// <auto-generated />
using System;
using GuardLan.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GuardLan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GuardLanDbContext))]
    [Migration("20260723202110_AddAlertReviewLifecycle")]
    partial class AddAlertReviewLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GuardLan.Domain.Entities.DnsQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("WasBlocked")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClientIp");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Domain");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("ClientIp", "Domain", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("dns_queries", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.IntegrationHealth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("LastCheckedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFailureUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RecordsImported")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsRejected")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<bool>("SourceAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("SourceEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("StaleAfterUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("LastCheckedUtc");

                    b.HasIndex("Source")
                        .IsUnique();

                    b.HasIndex("StaleAfterUtc");

                    b.HasIndex("Status");

                    b.ToTable("integration_health", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.IntegrationImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("RecordsImported")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("integer");

                    b.Property<int>("RecordsRejected")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<bool>("SourceAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("SourceEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedUtc");

                    b.HasIndex("Kind");

                    b.HasIndex("Source");

                    b.HasIndex("Status");

                    b.ToTable("integration_import_runs", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.MdacRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("RegisteredUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("mdac_registrations", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.MdacSyncRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ForegroundSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("SyncedUtc");

                    b.ToTable("mdac_sync_records", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.NetworkConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("BytesReceived")
                        .HasColumnType("bigint");

                    b.Property<long>("BytesSent")
                        .HasColumnType("bigint");

                    b.Property<string>("DestinationDomain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DestinationIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("DestinationPort")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.HasKey("Id");

                    b.HasIndex("DestinationDomain");

                    b.HasIndex("DeviceId");

                    b.HasIndex("LastSeenUtc");

                    b.HasIndex("Source", "SourceRecordId");

                    b.ToTable("network_connections", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.NetworkDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("FirstSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Hostname")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrusted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("IpAddress");

                    b.HasIndex("MacAddress")
                        .IsUnique();

                    b.ToTable("network_devices", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.NetworkScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DevicesDiscovered")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FinishedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("RequestedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Subnet")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RequestedUtc");

                    b.ToTable("network_scan_runs", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.SecurityAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DestinationIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("DestinationPort")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EvidenceSummary")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Protocol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("ResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("Open");

                    b.Property<DateTime?>("ReviewedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ResolvedUtc");

                    b.HasIndex("ReviewStatus");

                    b.HasIndex("ReviewedUtc");

                    b.HasIndex("Source", "SourceRecordId");

                    b.ToTable("security_alerts", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.SecurityAlertHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("SecurityAlertId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("SecurityAlertId");

                    b.ToTable("security_alert_history", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.TlsObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alpn")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Cipher")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("DestinationPort")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ja3")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Ja3s")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("ObservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceRecordId")
                        .HasMaxLength(96)
                        .HasColumnType("character varying(96)");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool?>("WasEstablished")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ObservedUtc");

                    b.HasIndex("ServerName");

                    b.HasIndex("Source", "SourceRecordId");

                    b.ToTable("tls_observations", (string)null);
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.DnsQuery", b =>
                {
                    b.HasOne("GuardLan.Domain.Entities.NetworkDevice", "Device")
                        .WithMany("DnsQueries")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.NetworkConnection", b =>
                {
                    b.HasOne("GuardLan.Domain.Entities.NetworkDevice", "Device")
                        .WithMany("Connections")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.SecurityAlert", b =>
                {
                    b.HasOne("GuardLan.Domain.Entities.NetworkConnection", "Connection")
                        .WithMany("Alerts")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GuardLan.Domain.Entities.NetworkDevice", "Device")
                        .WithMany("Alerts")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Connection");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.SecurityAlertHistory", b =>
                {
                    b.HasOne("GuardLan.Domain.Entities.SecurityAlert", "SecurityAlert")
                        .WithMany("History")
                        .HasForeignKey("SecurityAlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityAlert");
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.TlsObservation", b =>
                {
                    b.HasOne("GuardLan.Domain.Entities.NetworkConnection", "Connection")
                        .WithMany("TlsObservations")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GuardLan.Domain.Entities.NetworkDevice", "Device")
                        .WithMany("TlsObservations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Connection");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.NetworkConnection", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("TlsObservations");
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.NetworkDevice", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Connections");

                    b.Navigation("DnsQueries");

                    b.Navigation("TlsObservations");
                });

            modelBuilder.Entity("GuardLan.Domain.Entities.SecurityAlert", b =>
                {
                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
